# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('version', models.CharField(max_length=32)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
