# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The application name as it is seen on the device', max_length=128)),
                ('description', models.TextField(blank=True, help_text='A short description text to help users identifying the correct app', null=True)),
                ('version', models.CharField(max_length=32, verbose_name='app version')),
                ('app_platform', models.CharField(choices=[('0', 'iOS'), ('1', 'Android')], default='0', max_length=1)),
                ('app_binary', models.FileField(help_text='This should have the following file extensions: <code>.ipa</code> for iOS and <code>.apk</code> for Android apps', upload_to='/Users/carsten/repositories/ey/fasttrack/uploads/apps', verbose_name='Application Binary')),
                ('app_icon', models.FileField(help_text='An application icon. Recommended size 512x512px', upload_to='/Users/carsten/repositories/ey/fasttrack/uploads/apps', verbose_name='Icon')),
                ('app_manifest', models.FileField(blank=True, help_text='[Optional] field for iOS manifest files (<code>.plist</code>)', null=True, upload_to='/Users/carsten/repositories/ey/fasttrack/uploads/apps', verbose_name='Manifest')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
    ]
